#!/bin/bash

echo "🚀 Starting Hermes LLM..."

# start LLM server (IMPORTANT)
 /app/llm/hermes.llamafile \
    --server \
    --host 0.0.0.0 \
    --port 8080 &

sleep 5

echo "🎙️ Starting Voice Server..."

uvicorn server:app \
    --host 0.0.0.0 \
    --port 5000 \
    --ssl-certfile=192.168.29.151+1.pem \
    --ssl-keyfile=192.168.29.151+1-key.pem